PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_MAIL_HEADER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_MAIL_HEADER-PROGRAM_NAME .
    FIELD ZV_MAIL_HEADER-CONFIGURATION .
    FIELD ZV_MAIL_HEADER-ADDRTYPE .
    FIELD ZV_MAIL_HEADER-SENDER .
    FIELD ZV_MAIL_HEADER-DISPLAY_NAME .
    FIELD ZV_MAIL_HEADER-SUBJECT .
    FIELD ZV_MAIL_HEADER-EXPRESS .
    FIELD ZV_MAIL_HEADER-IMMEDIATELY .
    FIELD ZV_MAIL_HEADER-DISABLE_USER .
    FIELD ZV_MAIL_HEADER-DISABLE_SENDING .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_MAIL_HEADER-PROGRAM_NAME .
    FIELD ZV_MAIL_HEADER-CONFIGURATION .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.