PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_MAIL_LIST CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_MAIL_LIST-MAILING_LIST .
    FIELD ZV_MAIL_LIST-ITEM .
    FIELD ZV_MAIL_LIST-ADDRTYPE .
    FIELD ZV_MAIL_LIST-RECIPIENT .
    FIELD ZV_MAIL_LIST-DISPLAY_NAME .
    FIELD ZV_MAIL_LIST-USER_FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_MAIL_LIST-MAILING_LIST .
    FIELD ZV_MAIL_LIST-ITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.