*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 18.08.2020 at 12:11:03
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZV_MAIL_BLOCK...................................*
TABLES: ZV_MAIL_BLOCK, *ZV_MAIL_BLOCK. "view work areas
CONTROLS: TCTRL_ZV_MAIL_BLOCK
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZV_MAIL_BLOCK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_MAIL_BLOCK.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_MAIL_BLOCK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_BLOCK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_BLOCK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_MAIL_BLOCK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_BLOCK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_BLOCK_TOTAL.

*...processing: ZV_MAIL_HEADER..................................*
TABLES: ZV_MAIL_HEADER, *ZV_MAIL_HEADER. "view work areas
CONTROLS: TCTRL_ZV_MAIL_HEADER
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZV_MAIL_HEADER. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_MAIL_HEADER.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_MAIL_HEADER_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_HEADER.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_HEADER_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_MAIL_HEADER_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_HEADER.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_HEADER_TOTAL.

*...processing: ZV_MAIL_LIST....................................*
TABLES: ZV_MAIL_LIST, *ZV_MAIL_LIST. "view work areas
CONTROLS: TCTRL_ZV_MAIL_LIST
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZV_MAIL_LIST. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_MAIL_LIST.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_MAIL_LIST_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_LIST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_LIST_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_MAIL_LIST_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_LIST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_LIST_TOTAL.

*...processing: ZV_MAIL_PROGRAM.................................*
TABLES: ZV_MAIL_PROGRAM, *ZV_MAIL_PROGRAM. "view work areas
CONTROLS: TCTRL_ZV_MAIL_PROGRAM
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZV_MAIL_PROGRAM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_MAIL_PROGRAM.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_MAIL_PROGRAM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_PROGRAM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_PROGRAM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_MAIL_PROGRAM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_PROGRAM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_PROGRAM_TOTAL.

*...processing: ZV_MAIL_RECIP...................................*
TABLES: ZV_MAIL_RECIP, *ZV_MAIL_RECIP. "view work areas
CONTROLS: TCTRL_ZV_MAIL_RECIP
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZV_MAIL_RECIP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_MAIL_RECIP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_MAIL_RECIP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_RECIP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_RECIP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_MAIL_RECIP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_MAIL_RECIP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_MAIL_RECIP_TOTAL.

*.........table declarations:.................................*
TABLES: ZBC_MAIL_BLOCK                 .
TABLES: ZBC_MAIL_HEADER                .
TABLES: ZBC_MAIL_LIST                  .
TABLES: ZBC_MAIL_PROGRAM               .
TABLES: ZBC_MAIL_RECIP                 .