PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZV_FILE_SERVER-SERVER_ID .
    FIELD ZV_FILE_SERVER-PROTOCOL .
    FIELD ZV_FILE_SERVER-HOSTNAME .
    FIELD ZV_FILE_SERVER-PORT .
    FIELD ZV_FILE_SERVER-URL .
    FIELD ZV_FILE_SERVER-USERNAME .
    FIELD ZV_FILE_SERVER-PASSWORD .
    FIELD ZV_FILE_SERVER-RFC_DESTINATION .
    FIELD ZV_FILE_SERVER-FINGERPRINT_INITIALIZED .
    FIELD ZV_FILE_SERVER-SIGN_FILE .
    FIELD ZV_FILE_SERVER-SIGNED_FILE_NAME .
    FIELD ZV_FILE_SERVER-SIGN_APPLICATION .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZV_FILE_SERVER-SERVER_ID .
  module detail_pai.
 endchain.