PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_FILE_SERVER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_FILE_SERVER-SERVER_ID .
    FIELD ZV_FILE_SERVER-PROTOCOL .
    FIELD ZV_FILE_SERVER-HOSTNAME .
    FIELD ZV_FILE_SERVER-PORT .
    FIELD ZV_FILE_SERVER-URL .
    FIELD ZV_FILE_SERVER-USERNAME .
    FIELD ZV_FILE_SERVER-PASSWORD .
    FIELD ZV_FILE_SERVER-RFC_DESTINATION .
    FIELD ZV_FILE_SERVER-FINGERPRINT_INITIALIZED .
    FIELD ZV_FILE_SERVER-SIGN_FILE .
    FIELD ZV_FILE_SERVER-SIGNED_FILE_NAME .
    FIELD ZV_FILE_SERVER-SIGN_APPLICATION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_FILE_SERVER-SERVER_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.