*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 01.09.2021 at 10:20:41
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZV_FILE_SERVER..................................*
FORM GET_DATA_ZV_FILE_SERVER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFILE_SERVER WHERE
(VIM_WHERETAB) .
    CLEAR ZV_FILE_SERVER .
ZV_FILE_SERVER-MANDT =
ZFILE_SERVER-MANDT .
ZV_FILE_SERVER-SERVER_ID =
ZFILE_SERVER-SERVER_ID .
ZV_FILE_SERVER-PROTOCOL =
ZFILE_SERVER-PROTOCOL .
ZV_FILE_SERVER-HOSTNAME =
ZFILE_SERVER-HOSTNAME .
ZV_FILE_SERVER-PORT =
ZFILE_SERVER-PORT .
ZV_FILE_SERVER-URL =
ZFILE_SERVER-URL .
ZV_FILE_SERVER-USERNAME =
ZFILE_SERVER-USERNAME .
ZV_FILE_SERVER-PASSWORD =
ZFILE_SERVER-PASSWORD .
ZV_FILE_SERVER-RFC_DESTINATION =
ZFILE_SERVER-RFC_DESTINATION .
ZV_FILE_SERVER-FINGERPRINT_INITIALIZED =
ZFILE_SERVER-FINGERPRINT_INITIALIZED .
ZV_FILE_SERVER-SIGN_FILE =
ZFILE_SERVER-SIGN_FILE .
ZV_FILE_SERVER-SIGNED_FILE_NAME =
ZFILE_SERVER-SIGNED_FILE_NAME .
ZV_FILE_SERVER-SIGN_APPLICATION =
ZFILE_SERVER-SIGN_APPLICATION .
<VIM_TOTAL_STRUC> = ZV_FILE_SERVER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZV_FILE_SERVER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZV_FILE_SERVER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZV_FILE_SERVER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFILE_SERVER WHERE
  SERVER_ID = ZV_FILE_SERVER-SERVER_ID .
    IF SY-SUBRC = 0.
    DELETE ZFILE_SERVER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFILE_SERVER WHERE
  SERVER_ID = ZV_FILE_SERVER-SERVER_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFILE_SERVER.
    ENDIF.
ZFILE_SERVER-MANDT =
ZV_FILE_SERVER-MANDT .
ZFILE_SERVER-SERVER_ID =
ZV_FILE_SERVER-SERVER_ID .
ZFILE_SERVER-PROTOCOL =
ZV_FILE_SERVER-PROTOCOL .
ZFILE_SERVER-HOSTNAME =
ZV_FILE_SERVER-HOSTNAME .
ZFILE_SERVER-PORT =
ZV_FILE_SERVER-PORT .
ZFILE_SERVER-URL =
ZV_FILE_SERVER-URL .
ZFILE_SERVER-USERNAME =
ZV_FILE_SERVER-USERNAME .
ZFILE_SERVER-PASSWORD =
ZV_FILE_SERVER-PASSWORD .
ZFILE_SERVER-RFC_DESTINATION =
ZV_FILE_SERVER-RFC_DESTINATION .
ZFILE_SERVER-FINGERPRINT_INITIALIZED =
ZV_FILE_SERVER-FINGERPRINT_INITIALIZED .
ZFILE_SERVER-SIGN_FILE =
ZV_FILE_SERVER-SIGN_FILE .
ZFILE_SERVER-SIGNED_FILE_NAME =
ZV_FILE_SERVER-SIGNED_FILE_NAME .
ZFILE_SERVER-SIGN_APPLICATION =
ZV_FILE_SERVER-SIGN_APPLICATION .
    IF SY-SUBRC = 0.
    UPDATE ZFILE_SERVER ##WARN_OK.
    ELSE.
    INSERT ZFILE_SERVER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZV_FILE_SERVER-UPD_FLAG,
STATUS_ZV_FILE_SERVER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZV_FILE_SERVER.
  SELECT SINGLE * FROM ZFILE_SERVER WHERE
SERVER_ID = ZV_FILE_SERVER-SERVER_ID .
ZV_FILE_SERVER-MANDT =
ZFILE_SERVER-MANDT .
ZV_FILE_SERVER-SERVER_ID =
ZFILE_SERVER-SERVER_ID .
ZV_FILE_SERVER-PROTOCOL =
ZFILE_SERVER-PROTOCOL .
ZV_FILE_SERVER-HOSTNAME =
ZFILE_SERVER-HOSTNAME .
ZV_FILE_SERVER-PORT =
ZFILE_SERVER-PORT .
ZV_FILE_SERVER-URL =
ZFILE_SERVER-URL .
ZV_FILE_SERVER-USERNAME =
ZFILE_SERVER-USERNAME .
ZV_FILE_SERVER-PASSWORD =
ZFILE_SERVER-PASSWORD .
ZV_FILE_SERVER-RFC_DESTINATION =
ZFILE_SERVER-RFC_DESTINATION .
ZV_FILE_SERVER-FINGERPRINT_INITIALIZED =
ZFILE_SERVER-FINGERPRINT_INITIALIZED .
ZV_FILE_SERVER-SIGN_FILE =
ZFILE_SERVER-SIGN_FILE .
ZV_FILE_SERVER-SIGNED_FILE_NAME =
ZFILE_SERVER-SIGNED_FILE_NAME .
ZV_FILE_SERVER-SIGN_APPLICATION =
ZFILE_SERVER-SIGN_APPLICATION .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZV_FILE_SERVER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZV_FILE_SERVER-SERVER_ID TO
ZFILE_SERVER-SERVER_ID .
MOVE ZV_FILE_SERVER-MANDT TO
ZFILE_SERVER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFILE_SERVER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFILE_SERVER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFILE_SERVER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*