*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZV_FILE_SERVERU01.
                    "VIEWFRAME_ZV_FILE_SERVER
INCLUDE LZV_FILE_SERVERU02.
                    "VIEWPROC_ZV_FILE_SERVER