PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_PROCES.

MODULE %_S_FILE.

MODULE %_S_UDATE.

MODULE %_S_UTIME.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD  S_PROCES-LOW.
  MODULE %_S_PROCES.
ENDCHAIN.


CHAIN.
  FIELD  S_PROCES-LOW.
    MODULE %_BLOCK_1000000.
ENDCHAIN.

FIELD !P_RESIND MODULE %_P_RESIND .

FIELD !P_FOLDER MODULE %_P_FOLDER .

CHAIN.
  FIELD  S_FILE-LOW.
  MODULE %_S_FILE.
ENDCHAIN.

FIELD !P_DPCHK MODULE %_P_DPCHK .

FIELD !P_RESEND MODULE %_P_RESEND .

CHAIN.
  FIELD  S_UDATE-LOW.
  FIELD  S_UDATE-HIGH.
  MODULE %_S_UDATE.
ENDCHAIN.

CHAIN.
  FIELD  S_UTIME-LOW.
  FIELD  S_UTIME-HIGH.
  MODULE %_S_UTIME.
ENDCHAIN.

FIELD !P_EMAIL MODULE %_P_EMAIL .

FIELD !P_VARIAN MODULE %_P_VARIAN .


CHAIN.
  FIELD P_RESIND .
  FIELD P_FOLDER .
  FIELD  S_FILE-LOW.
  FIELD P_DPCHK .
  FIELD P_RESEND .
  FIELD  S_UDATE-LOW.
  FIELD  S_UDATE-HIGH.
  FIELD  S_UTIME-LOW.
  FIELD  S_UTIME-HIGH.
  FIELD P_EMAIL .
  FIELD P_VARIAN .
    MODULE %_BLOCK_1000003.
ENDCHAIN.

CHAIN.
  FIELD  S_PROCES-LOW.
  FIELD P_RESIND .
  FIELD P_FOLDER .
  FIELD  S_FILE-LOW.
  FIELD P_DPCHK .
  FIELD P_RESEND .
  FIELD  S_UDATE-LOW.
  FIELD  S_UDATE-HIGH.
  FIELD  S_UTIME-LOW.
  FIELD  S_UTIME-HIGH.
  FIELD P_EMAIL .
  FIELD P_VARIAN .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.