*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFAM_LOGU01.
                    "TABLEFRAME_ZFAM_LOG
INCLUDE LZFAM_LOGU02.
                    "TABLEPROC_ZFAM_LOG