PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFAM_RULES_GROUP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFAM_RULES_GROUP-GROUP_ID .
    FIELD ZFAM_RULES_GROUP-CRITERIAS_GROUP .
    FIELD ZFAM_RULES_GROUP-CRITERIA .
    FIELD ZFAM_RULES_GROUP-ITEM .
    FIELD ZFAM_RULES_GROUP-SIGN .
    FIELD ZFAM_RULES_GROUP-OPTI .
    FIELD ZFAM_RULES_GROUP-LOW .
    FIELD ZFAM_RULES_GROUP-HIGH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFAM_RULES_GROUP-GROUP_ID .
    FIELD ZFAM_RULES_GROUP-CRITERIAS_GROUP .
    FIELD ZFAM_RULES_GROUP-CRITERIA .
    FIELD ZFAM_RULES_GROUP-ITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.