PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFAM_PARAMETERS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFAM_PARAMETERS-FEATURE_ID .
    FIELD ZFAM_PARAMETERS-PARAMETER_NAME .
    FIELD ZFAM_PARAMETERS-ITEM .
    FIELD ZFAM_PARAMETERS-PARAMETER_VALUE .
    FIELD ZFAM_PARAMETERS-RULE_LEVEL .
    FIELD ZFAM_PARAMETERS-GROUP_ID .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFAM_PARAMETERS-FEATURE_ID .
    FIELD ZFAM_PARAMETERS-PARAMETER_NAME .
    FIELD ZFAM_PARAMETERS-ITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.