PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_FAM_PARAMETER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_FAM_PARAMETER-PARAMETER_NAME .
    FIELD ZV_FAM_PARAMETER-ITEM .
    FIELD ZV_FAM_PARAMETER-PARAMETER_VALUE .
    FIELD ZV_FAM_PARAMETER-RULE_LEVEL .
    FIELD ZV_FAM_PARAMETER-GROUP_ID .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_FAM_PARAMETER-PARAMETER_NAME .
    FIELD ZV_FAM_PARAMETER-ITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.