PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBC_MAIL_RECIP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBC_MAIL_RECIP-PROGRAM_NAME .
    FIELD ZBC_MAIL_RECIP-CONFIGURATION .
    FIELD ZBC_MAIL_RECIP-ITEM .
    FIELD ZBC_MAIL_RECIP-ADDRTYPE .
    FIELD ZBC_MAIL_RECIP-RECIPIENT .
    FIELD ZBC_MAIL_RECIP-DISPLAY_NAME .
    FIELD ZBC_MAIL_RECIP-USER_FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBC_MAIL_RECIP-PROGRAM_NAME .
    FIELD ZBC_MAIL_RECIP-CONFIGURATION .
    FIELD ZBC_MAIL_RECIP-ITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.