PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBC_MAIL_BLOCK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBC_MAIL_BLOCK-PROGRAM_NAME .
    FIELD ZBC_MAIL_BLOCK-CONFIGURATION .
    FIELD ZBC_MAIL_BLOCK-BLOCK_NAME .
    FIELD ZBC_MAIL_BLOCK-BLOCK_FORMAT .
    FIELD ZBC_MAIL_BLOCK-ATTACHMENT .
    FIELD ZBC_MAIL_BLOCK-ATTACH_SUBJECT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBC_MAIL_BLOCK-PROGRAM_NAME .
    FIELD ZBC_MAIL_BLOCK-CONFIGURATION .
    FIELD ZBC_MAIL_BLOCK-BLOCK_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.