*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZBC_MAIL_TABLESU03.
                    "ZBC_RECEIVE_TABLE_CONTENT
INCLUDE LZBC_MAIL_TABLESU01.
                    "TABLEFRAME_ZBC_MAIL_TABLES
INCLUDE LZBC_MAIL_TABLESU02.
                    "TABLEPROC_ZBC_MAIL_TABLES