*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZDATA_TABLESU01.
                    "TABLEFRAME_ZDATA_TABLES
INCLUDE LZDATA_TABLESU02.
                    "TABLEPROC_ZDATA_TABLES