PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZV_FILE_TRANSFER-PROCESS_ID .
    FIELD ZV_FILE_TRANSFER-SERVER_ID .
    FIELD ZV_FILE_TRANSFER-TARGET_FOLDER .
    FIELD ZV_FILE_TRANSFER-END_TARGET_FOLDER .
    FIELD ZV_FILE_TRANSFER-DELTA_MODE .
    FIELD ZV_FILE_TRANSFER-TRIGGER_FILE .
    FIELD ZV_FILE_TRANSFER-TRIGGER_FILE_NAME .
    FIELD ZV_FILE_TRANSFER-TRIGGER_FILE_VERSION .
    FIELD ZV_FILE_TRANSFER-PHYSICAL_TRANSFER .
    FIELD ZV_FILE_TRANSFER-SIGN_FILE .
    FIELD ZV_FILE_TRANSFER-DUPLICATE_CHECK .
    FIELD ZV_FILE_TRANSFER-MOVE_TO_PROGRESS .
    FIELD ZV_FILE_TRANSFER-ARCHIVE_FILE .
    FIELD ZV_FILE_TRANSFER-PARK_FILE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZV_FILE_TRANSFER-PROCESS_ID .
  module detail_pai.
 endchain.