PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_FILE_TRANSFER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_FILE_TRANSFER-PROCESS_ID .
    FIELD ZV_FILE_TRANSFER-SERVER_ID .
    FIELD ZV_FILE_TRANSFER-TARGET_FOLDER .
    FIELD ZV_FILE_TRANSFER-END_TARGET_FOLDER .
    FIELD ZV_FILE_TRANSFER-DELTA_MODE .
    FIELD ZV_FILE_TRANSFER-TRIGGER_FILE .
    FIELD ZV_FILE_TRANSFER-TRIGGER_FILE_NAME .
    FIELD ZV_FILE_TRANSFER-TRIGGER_FILE_VERSION .
    FIELD ZV_FILE_TRANSFER-PHYSICAL_TRANSFER .
    FIELD ZV_FILE_TRANSFER-SIGN_FILE .
    FIELD ZV_FILE_TRANSFER-DUPLICATE_CHECK .
    FIELD ZV_FILE_TRANSFER-MOVE_TO_PROGRESS .
    FIELD ZV_FILE_TRANSFER-ARCHIVE_FILE .
    FIELD ZV_FILE_TRANSFER-PARK_FILE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_FILE_TRANSFER-PROCESS_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.