*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZV_FILE_TRANSFERU01.
                    "VIEWFRAME_ZV_FILE_TRANSFER
INCLUDE LZV_FILE_TRANSFERU02.
                    "VIEWPROC_ZV_FILE_TRANSFER