*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 01.09.2021 at 10:17:38
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZV_FILE_TRANSFER................................*
FORM GET_DATA_ZV_FILE_TRANSFER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFILE_TRANSFER WHERE
(VIM_WHERETAB) .
    CLEAR ZV_FILE_TRANSFER .
ZV_FILE_TRANSFER-MANDT =
ZFILE_TRANSFER-MANDT .
ZV_FILE_TRANSFER-PROCESS_ID =
ZFILE_TRANSFER-PROCESS_ID .
ZV_FILE_TRANSFER-SERVER_ID =
ZFILE_TRANSFER-SERVER_ID .
ZV_FILE_TRANSFER-TARGET_FOLDER =
ZFILE_TRANSFER-TARGET_FOLDER .
ZV_FILE_TRANSFER-END_TARGET_FOLDER =
ZFILE_TRANSFER-END_TARGET_FOLDER .
ZV_FILE_TRANSFER-DELTA_MODE =
ZFILE_TRANSFER-DELTA_MODE .
ZV_FILE_TRANSFER-TRIGGER_FILE =
ZFILE_TRANSFER-TRIGGER_FILE .
ZV_FILE_TRANSFER-TRIGGER_FILE_NAME =
ZFILE_TRANSFER-TRIGGER_FILE_NAME .
ZV_FILE_TRANSFER-TRIGGER_FILE_VERSION =
ZFILE_TRANSFER-TRIGGER_FILE_VERSION .
ZV_FILE_TRANSFER-PHYSICAL_TRANSFER =
ZFILE_TRANSFER-PHYSICAL_TRANSFER .
ZV_FILE_TRANSFER-SIGN_FILE =
ZFILE_TRANSFER-SIGN_FILE .
ZV_FILE_TRANSFER-DUPLICATE_CHECK =
ZFILE_TRANSFER-DUPLICATE_CHECK .
ZV_FILE_TRANSFER-MOVE_TO_PROGRESS =
ZFILE_TRANSFER-MOVE_TO_PROGRESS .
ZV_FILE_TRANSFER-ARCHIVE_FILE =
ZFILE_TRANSFER-ARCHIVE_FILE .
ZV_FILE_TRANSFER-PARK_FILE =
ZFILE_TRANSFER-PARK_FILE .
<VIM_TOTAL_STRUC> = ZV_FILE_TRANSFER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZV_FILE_TRANSFER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZV_FILE_TRANSFER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZV_FILE_TRANSFER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFILE_TRANSFER WHERE
  PROCESS_ID = ZV_FILE_TRANSFER-PROCESS_ID .
    IF SY-SUBRC = 0.
    DELETE ZFILE_TRANSFER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFILE_TRANSFER WHERE
  PROCESS_ID = ZV_FILE_TRANSFER-PROCESS_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFILE_TRANSFER.
    ENDIF.
ZFILE_TRANSFER-MANDT =
ZV_FILE_TRANSFER-MANDT .
ZFILE_TRANSFER-PROCESS_ID =
ZV_FILE_TRANSFER-PROCESS_ID .
ZFILE_TRANSFER-SERVER_ID =
ZV_FILE_TRANSFER-SERVER_ID .
ZFILE_TRANSFER-TARGET_FOLDER =
ZV_FILE_TRANSFER-TARGET_FOLDER .
ZFILE_TRANSFER-END_TARGET_FOLDER =
ZV_FILE_TRANSFER-END_TARGET_FOLDER .
ZFILE_TRANSFER-DELTA_MODE =
ZV_FILE_TRANSFER-DELTA_MODE .
ZFILE_TRANSFER-TRIGGER_FILE =
ZV_FILE_TRANSFER-TRIGGER_FILE .
ZFILE_TRANSFER-TRIGGER_FILE_NAME =
ZV_FILE_TRANSFER-TRIGGER_FILE_NAME .
ZFILE_TRANSFER-TRIGGER_FILE_VERSION =
ZV_FILE_TRANSFER-TRIGGER_FILE_VERSION .
ZFILE_TRANSFER-PHYSICAL_TRANSFER =
ZV_FILE_TRANSFER-PHYSICAL_TRANSFER .
ZFILE_TRANSFER-SIGN_FILE =
ZV_FILE_TRANSFER-SIGN_FILE .
ZFILE_TRANSFER-DUPLICATE_CHECK =
ZV_FILE_TRANSFER-DUPLICATE_CHECK .
ZFILE_TRANSFER-MOVE_TO_PROGRESS =
ZV_FILE_TRANSFER-MOVE_TO_PROGRESS .
ZFILE_TRANSFER-ARCHIVE_FILE =
ZV_FILE_TRANSFER-ARCHIVE_FILE .
ZFILE_TRANSFER-PARK_FILE =
ZV_FILE_TRANSFER-PARK_FILE .
    IF SY-SUBRC = 0.
    UPDATE ZFILE_TRANSFER ##WARN_OK.
    ELSE.
    INSERT ZFILE_TRANSFER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZV_FILE_TRANSFER-UPD_FLAG,
STATUS_ZV_FILE_TRANSFER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZV_FILE_TRANSFER.
  SELECT SINGLE * FROM ZFILE_TRANSFER WHERE
PROCESS_ID = ZV_FILE_TRANSFER-PROCESS_ID .
ZV_FILE_TRANSFER-MANDT =
ZFILE_TRANSFER-MANDT .
ZV_FILE_TRANSFER-PROCESS_ID =
ZFILE_TRANSFER-PROCESS_ID .
ZV_FILE_TRANSFER-SERVER_ID =
ZFILE_TRANSFER-SERVER_ID .
ZV_FILE_TRANSFER-TARGET_FOLDER =
ZFILE_TRANSFER-TARGET_FOLDER .
ZV_FILE_TRANSFER-END_TARGET_FOLDER =
ZFILE_TRANSFER-END_TARGET_FOLDER .
ZV_FILE_TRANSFER-DELTA_MODE =
ZFILE_TRANSFER-DELTA_MODE .
ZV_FILE_TRANSFER-TRIGGER_FILE =
ZFILE_TRANSFER-TRIGGER_FILE .
ZV_FILE_TRANSFER-TRIGGER_FILE_NAME =
ZFILE_TRANSFER-TRIGGER_FILE_NAME .
ZV_FILE_TRANSFER-TRIGGER_FILE_VERSION =
ZFILE_TRANSFER-TRIGGER_FILE_VERSION .
ZV_FILE_TRANSFER-PHYSICAL_TRANSFER =
ZFILE_TRANSFER-PHYSICAL_TRANSFER .
ZV_FILE_TRANSFER-SIGN_FILE =
ZFILE_TRANSFER-SIGN_FILE .
ZV_FILE_TRANSFER-DUPLICATE_CHECK =
ZFILE_TRANSFER-DUPLICATE_CHECK .
ZV_FILE_TRANSFER-MOVE_TO_PROGRESS =
ZFILE_TRANSFER-MOVE_TO_PROGRESS .
ZV_FILE_TRANSFER-ARCHIVE_FILE =
ZFILE_TRANSFER-ARCHIVE_FILE .
ZV_FILE_TRANSFER-PARK_FILE =
ZFILE_TRANSFER-PARK_FILE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZV_FILE_TRANSFER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZV_FILE_TRANSFER-PROCESS_ID TO
ZFILE_TRANSFER-PROCESS_ID .
MOVE ZV_FILE_TRANSFER-MANDT TO
ZFILE_TRANSFER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFILE_TRANSFER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFILE_TRANSFER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFILE_TRANSFER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*