PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_PROC_HEADER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_PROC_HEADER-PROCESS_ID .
    FIELD ZV_PROC_HEADER-PROCESS_DESCRIPTION .
    FIELD ZV_PROC_HEADER-PARENT_PROCESS .
    FIELD ZV_PROC_HEADER-PROCESS_TYPE .
    FIELD ZV_PROC_HEADER-BUSINESS_DOC_URL .
    FIELD ZV_PROC_HEADER-FUNCTIONNAL_DOC_URL .
    FIELD ZV_PROC_HEADER-TECHNICAL_DOC_URL .
    FIELD ZV_PROC_HEADER-PROGRAM_NAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_PROC_HEADER-PROCESS_ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.