PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZV_PROC_HEADER-PROCESS_ID .
    FIELD ZV_PROC_HEADER-PROCESS_DESCRIPTION .
    FIELD ZV_PROC_HEADER-PARENT_PROCESS .
    FIELD ZV_PROC_HEADER-PROCESS_TYPE .
    FIELD ZV_PROC_HEADER-BUSINESS_DOC_URL .
    FIELD ZV_PROC_HEADER-FUNCTIONNAL_DOC_URL .
    FIELD ZV_PROC_HEADER-TECHNICAL_DOC_URL .
    FIELD ZV_PROC_HEADER-PROGRAM_NAME .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZV_PROC_HEADER-PROCESS_ID .
  module detail_pai.
 endchain.