*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCORE_TABLESU03.
                    "VIEWFRAME_ZV_PROC_TEXT
INCLUDE LZCORE_TABLESU04.
                    "VIEWPROC_ZV_PROC_TEXT
INCLUDE LZCORE_TABLESU01.
                    "VIEWFRAME_ZV_PROC_HEADER
INCLUDE LZCORE_TABLESU02.
                    "VIEWPROC_ZV_PROC_HEADER