*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 01.09.2021 at 10:14:30
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZV_FILE_MANAGER.................................*
FORM GET_DATA_ZV_FILE_MANAGER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFILE_MANAGER WHERE
(VIM_WHERETAB) .
    CLEAR ZV_FILE_MANAGER .
ZV_FILE_MANAGER-MANDT =
ZFILE_MANAGER-MANDT .
ZV_FILE_MANAGER-PROCESS_ID =
ZFILE_MANAGER-PROCESS_ID .
ZV_FILE_MANAGER-ROOT_LOGICAL =
ZFILE_MANAGER-ROOT_LOGICAL .
ZV_FILE_MANAGER-ROOT_FOLDER =
ZFILE_MANAGER-ROOT_FOLDER .
ZV_FILE_MANAGER-FILE_PATTERN =
ZFILE_MANAGER-FILE_PATTERN .
ZV_FILE_MANAGER-PROGRESS_LOGICAL =
ZFILE_MANAGER-PROGRESS_LOGICAL .
ZV_FILE_MANAGER-PROGRESS_FOLDER =
ZFILE_MANAGER-PROGRESS_FOLDER .
ZV_FILE_MANAGER-ARCHIVE_LOGICAL =
ZFILE_MANAGER-ARCHIVE_LOGICAL .
ZV_FILE_MANAGER-ARCHIVE_FOLDER =
ZFILE_MANAGER-ARCHIVE_FOLDER .
ZV_FILE_MANAGER-ARCHIVED_FILE_NAME =
ZFILE_MANAGER-ARCHIVED_FILE_NAME .
ZV_FILE_MANAGER-ERROR_LOGICAL =
ZFILE_MANAGER-ERROR_LOGICAL .
ZV_FILE_MANAGER-ERROR_FOLDER =
ZFILE_MANAGER-ERROR_FOLDER .
ZV_FILE_MANAGER-ERROR_FILE_NAME =
ZFILE_MANAGER-ERROR_FILE_NAME .
ZV_FILE_MANAGER-RETENTION =
ZFILE_MANAGER-RETENTION .
ZV_FILE_MANAGER-USE_METADATA =
ZFILE_MANAGER-USE_METADATA .
ZV_FILE_MANAGER-METADATA_VERSION =
ZFILE_MANAGER-METADATA_VERSION .
ZV_FILE_MANAGER-FILE_TYPE =
ZFILE_MANAGER-FILE_TYPE .
ZV_FILE_MANAGER-DELTA_MODE =
ZFILE_MANAGER-DELTA_MODE .
ZV_FILE_MANAGER-FILTER_METHOD =
ZFILE_MANAGER-FILTER_METHOD .
<VIM_TOTAL_STRUC> = ZV_FILE_MANAGER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZV_FILE_MANAGER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZV_FILE_MANAGER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZV_FILE_MANAGER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFILE_MANAGER WHERE
  PROCESS_ID = ZV_FILE_MANAGER-PROCESS_ID .
    IF SY-SUBRC = 0.
    DELETE ZFILE_MANAGER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFILE_MANAGER WHERE
  PROCESS_ID = ZV_FILE_MANAGER-PROCESS_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFILE_MANAGER.
    ENDIF.
ZFILE_MANAGER-MANDT =
ZV_FILE_MANAGER-MANDT .
ZFILE_MANAGER-PROCESS_ID =
ZV_FILE_MANAGER-PROCESS_ID .
ZFILE_MANAGER-ROOT_LOGICAL =
ZV_FILE_MANAGER-ROOT_LOGICAL .
ZFILE_MANAGER-ROOT_FOLDER =
ZV_FILE_MANAGER-ROOT_FOLDER .
ZFILE_MANAGER-FILE_PATTERN =
ZV_FILE_MANAGER-FILE_PATTERN .
ZFILE_MANAGER-PROGRESS_LOGICAL =
ZV_FILE_MANAGER-PROGRESS_LOGICAL .
ZFILE_MANAGER-PROGRESS_FOLDER =
ZV_FILE_MANAGER-PROGRESS_FOLDER .
ZFILE_MANAGER-ARCHIVE_LOGICAL =
ZV_FILE_MANAGER-ARCHIVE_LOGICAL .
ZFILE_MANAGER-ARCHIVE_FOLDER =
ZV_FILE_MANAGER-ARCHIVE_FOLDER .
ZFILE_MANAGER-ARCHIVED_FILE_NAME =
ZV_FILE_MANAGER-ARCHIVED_FILE_NAME .
ZFILE_MANAGER-ERROR_LOGICAL =
ZV_FILE_MANAGER-ERROR_LOGICAL .
ZFILE_MANAGER-ERROR_FOLDER =
ZV_FILE_MANAGER-ERROR_FOLDER .
ZFILE_MANAGER-ERROR_FILE_NAME =
ZV_FILE_MANAGER-ERROR_FILE_NAME .
ZFILE_MANAGER-RETENTION =
ZV_FILE_MANAGER-RETENTION .
ZFILE_MANAGER-USE_METADATA =
ZV_FILE_MANAGER-USE_METADATA .
ZFILE_MANAGER-METADATA_VERSION =
ZV_FILE_MANAGER-METADATA_VERSION .
ZFILE_MANAGER-FILE_TYPE =
ZV_FILE_MANAGER-FILE_TYPE .
ZFILE_MANAGER-DELTA_MODE =
ZV_FILE_MANAGER-DELTA_MODE .
ZFILE_MANAGER-FILTER_METHOD =
ZV_FILE_MANAGER-FILTER_METHOD .
    IF SY-SUBRC = 0.
    UPDATE ZFILE_MANAGER ##WARN_OK.
    ELSE.
    INSERT ZFILE_MANAGER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZV_FILE_MANAGER-UPD_FLAG,
STATUS_ZV_FILE_MANAGER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZV_FILE_MANAGER.
  SELECT SINGLE * FROM ZFILE_MANAGER WHERE
PROCESS_ID = ZV_FILE_MANAGER-PROCESS_ID .
ZV_FILE_MANAGER-MANDT =
ZFILE_MANAGER-MANDT .
ZV_FILE_MANAGER-PROCESS_ID =
ZFILE_MANAGER-PROCESS_ID .
ZV_FILE_MANAGER-ROOT_LOGICAL =
ZFILE_MANAGER-ROOT_LOGICAL .
ZV_FILE_MANAGER-ROOT_FOLDER =
ZFILE_MANAGER-ROOT_FOLDER .
ZV_FILE_MANAGER-FILE_PATTERN =
ZFILE_MANAGER-FILE_PATTERN .
ZV_FILE_MANAGER-PROGRESS_LOGICAL =
ZFILE_MANAGER-PROGRESS_LOGICAL .
ZV_FILE_MANAGER-PROGRESS_FOLDER =
ZFILE_MANAGER-PROGRESS_FOLDER .
ZV_FILE_MANAGER-ARCHIVE_LOGICAL =
ZFILE_MANAGER-ARCHIVE_LOGICAL .
ZV_FILE_MANAGER-ARCHIVE_FOLDER =
ZFILE_MANAGER-ARCHIVE_FOLDER .
ZV_FILE_MANAGER-ARCHIVED_FILE_NAME =
ZFILE_MANAGER-ARCHIVED_FILE_NAME .
ZV_FILE_MANAGER-ERROR_LOGICAL =
ZFILE_MANAGER-ERROR_LOGICAL .
ZV_FILE_MANAGER-ERROR_FOLDER =
ZFILE_MANAGER-ERROR_FOLDER .
ZV_FILE_MANAGER-ERROR_FILE_NAME =
ZFILE_MANAGER-ERROR_FILE_NAME .
ZV_FILE_MANAGER-RETENTION =
ZFILE_MANAGER-RETENTION .
ZV_FILE_MANAGER-USE_METADATA =
ZFILE_MANAGER-USE_METADATA .
ZV_FILE_MANAGER-METADATA_VERSION =
ZFILE_MANAGER-METADATA_VERSION .
ZV_FILE_MANAGER-FILE_TYPE =
ZFILE_MANAGER-FILE_TYPE .
ZV_FILE_MANAGER-DELTA_MODE =
ZFILE_MANAGER-DELTA_MODE .
ZV_FILE_MANAGER-FILTER_METHOD =
ZFILE_MANAGER-FILTER_METHOD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZV_FILE_MANAGER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZV_FILE_MANAGER-PROCESS_ID TO
ZFILE_MANAGER-PROCESS_ID .
MOVE ZV_FILE_MANAGER-MANDT TO
ZFILE_MANAGER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFILE_MANAGER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFILE_MANAGER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFILE_MANAGER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*