*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZV_FILE_MANAGERU01.
                    "VIEWFRAME_ZV_FILE_MANAGER
INCLUDE LZV_FILE_MANAGERU02.
                    "VIEWPROC_ZV_FILE_MANAGER