PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_PRCID.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_PROCID MODULE %_P_PROCID .

CHAIN.
  FIELD P_FLDCLN.
  FIELD P_FLDCHK.
  FIELD P_REPORT.
    MODULE %_RADIOBUTTON_GROUP_GRP1                          .
ENDCHAIN.

FIELD !P_ROOT MODULE %_P_ROOT .


CHAIN.
  FIELD P_PROCID .
  FIELD P_FLDCLN.
  FIELD P_FLDCHK.
  FIELD P_REPORT.
  FIELD P_ROOT .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

CHAIN.
  FIELD  S_PRCID-LOW.
  MODULE %_S_PRCID.
ENDCHAIN.


CHAIN.
  FIELD  S_PRCID-LOW.
    MODULE %_BLOCK_1000007.
ENDCHAIN.

CHAIN.
  FIELD P_PROCID .
  FIELD P_FLDCLN.
  FIELD P_FLDCHK.
  FIELD P_REPORT.
  FIELD P_ROOT .
  FIELD  S_PRCID-LOW.
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.