*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZBC_AUDIT_TABLESU01.
                    "TABLEFRAME_ZBC_AUDIT_TABLES
INCLUDE LZBC_AUDIT_TABLESU02.
                    "TABLEPROC_ZBC_AUDIT_TABLES