*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 04.07.2013 at 15:41:18 by user CRESSOD
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBC_AUDIT_TABLESTOP.              " Global Data
  INCLUDE LZBC_AUDIT_TABLESUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBC_AUDIT_TABLESF00                    . " subprograms
  INCLUDE LZBC_AUDIT_TABLESI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBC_AUDIT_TABLESF...              " Subprograms
* INCLUDE LZBC_AUDIT_TABLESO...              " PBO-Modules
* INCLUDE LZBC_AUDIT_TABLESI...              " PAI-Modules