*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ CONVERSION_EXIT_ZSIZE_INPUT

    IMPORTING
       REFERENCE(INPUT) TYPE !CLIKE
    EXPORTING
       REFERENCE(OUTPUT) TYPE !CLIKE .