*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFILE_CONVERSION_EXITU01.
                    "CONVERSION_EXIT_ZSIZE_INPUT
INCLUDE LZFILE_CONVERSION_EXITU02.
                    "CONVERSION_EXIT_ZSIZE_OUTPUT