*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZPROC_HEADERU01.
                    "TABLEFRAME_ZPROC_HEADER
INCLUDE LZPROC_HEADERU02.
                    "TABLEPROC_ZPROC_HEADER